name: CI/CD for Flask App on AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to AWS Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@your-instance-ip << 'EOF'
        cd /path/to/your/project
        git pull origin main
        source venv/bin/activate  # Adjust if you are using a virtual environment
        pip install -r requirements.txt
        sudo systemctl restart gunicorn  # Adjust based on your setup
        EOF
